import { createClient } from "@/lib/supabase/server";
import { notFound } from "next/navigation";
import Link from "next/link";

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata() {
  return { title: "Privacy Policy", robots: { index: false } };
}

export default async function DefaultPrivacyPage({ params }: Props) {
  const { slug } = await params;
  const supabase = await createClient();

  const { data: profile } = await supabase
    .from("profiles")
    .select("username, slug, using_default_privacy")
    .eq("slug", slug)
    .single();

  if (!profile || !profile.using_default_privacy) notFound();

  const today = new Date().toLocaleDateString("en-GB", {
    day: "numeric", month: "long", year: "numeric",
  });

  const section = (title: string, content: React.ReactNode) => (
    <section style={{ marginBottom: "28px" }}>
      <h2 style={{ fontSize: "15px", fontWeight: 500, color: "var(--text)", marginBottom: "8px" }}>{title}</h2>
      <div style={{ fontSize: "15px", color: "var(--muted)", lineHeight: "1.7" }}>{content}</div>
    </section>
  );

  return (
    <div className="h-screen flex flex-col overflow-hidden" style={{ background: "var(--cream)" }}>
      <div className="flex-1 overflow-y-auto">
        <div style={{ maxWidth: "600px", margin: "0 auto", padding: "40px 32px 60px" }}>

          <div style={{ marginBottom: "32px" }}>
            <Link href={`/to/${profile.slug}`} style={{ fontSize: "14px", color: "var(--muted)" }} className="hover:underline">
              ← Back to form
            </Link>
          </div>

          <h1 className="font-medium" style={{ fontSize: "28px", letterSpacing: "-0.01em", color: "var(--text)", marginBottom: "6px" }}>
            Privacy Policy
          </h1>
          <p style={{ fontSize: "13px", color: "var(--muted)", marginBottom: "40px" }}>Last updated: {today}</p>

          {section("1. Who is responsible for your data",
            <p>This contact form is operated by an independent individual or freelancer (the <strong style={{ color: "var(--text)" }}>Data Controller</strong>) who uses the ReachOut service provided by Apacheta Studio to receive messages from visitors. When you submit this form, your name, email address, and message are sent directly to the Data Controller&apos;s inbox. <strong style={{ color: "var(--text)" }}>Apacheta Studio acts solely as a data processor</strong> — it delivers your message and does not store, read, or retain your personal data.</p>
          )}

          {section("2. What data is collected",
            <>
              <ul style={{ paddingLeft: "18px", marginBottom: "10px" }}>
                <li>Your name</li>
                <li>Your email address</li>
                <li>The message you write</li>
              </ul>
              <p>No other data is collected. No cookies are set. No tracking scripts are loaded. Your IP address is not stored.</p>
            </>
          )}

          {section("3. How your data is used",
            <p>Your data is used solely to deliver your message to the Data Controller so they can respond to you. It is not used for marketing, profiling, or any other purpose.</p>
          )}

          {section("4. How long your data is retained",
            <p>Apacheta Studio retains your data only for the time necessary to deliver the email (typically seconds). After delivery, nothing is stored on Apacheta&apos;s infrastructure. The Data Controller may retain your message in their email inbox according to their own retention policies.</p>
          )}

          {section("5. Your rights",
            <p>Under the GDPR you have the right to access, correct, or request deletion of your personal data. To exercise these rights, contact the Data Controller directly by replying to any email correspondence, or by submitting a new message via this form.</p>
          )}

          {section("6. Infrastructure",
            <p>This service runs on EU-based infrastructure (Frankfurt, Germany). No data is transferred outside the European Economic Area.</p>
          )}

          <section>
            <p
              style={{
                fontSize: "13px", color: "var(--muted)",
                background: "var(--accent)", border: "1px solid var(--accent-dark)",
                borderRadius: "8px", padding: "12px 16px", lineHeight: "1.6"
              }}
            >
              <strong style={{ color: "var(--accent-dark)" }}>Note to the form owner:</strong> This is a default policy generated by ReachOut. You are the Data Controller and are responsible for ensuring this policy accurately reflects your data practices. Consider replacing this with your own policy once you have a website.
            </p>
          </section>

          <div style={{ marginTop: "40px", paddingTop: "24px", borderTop: "1px solid var(--border)", fontSize: "12px", color: "var(--muted)" }}>
            Delivered via <a href="/" style={{ color: "var(--teal)" }} className="hover:underline">ReachOut</a> by Apacheta Studio
          </div>
        </div>
      </div>
    </div>
  );
}
